# Generated by Django 6.0.4 on 2026-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_abonne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='email',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='abonne',
            name='telephone',
        ),
        migrations.AddField(
            model_name='abonne',
            name='contact',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abonne',
            name='mot_de_passe',
            field=models.CharField(default='inconnu', max_length=100),
            preserve_default=False,
        ),
    ]
